/*-------------------------------------------------------------------------
    This source file is a part of the MC6809 Simulator
    For the latest info, see http:www.marrin.org/
    Copyright (c) 2018-2024, Chris Marrin
    All rights reserved.
    Use of this source code is governed by the MIT license that can be
    found in the LICENSE file.
-------------------------------------------------------------------------*/
//
//  MC6809.cpp
//  6809 simulator
//
//  Created by Chris Marrin on 4/22/24.
//

#include "MC6809.h"

// Opcode table

// The 6809 has 2 extended opcodess Page2 (0x10) and Page3 (0x11). These
// typically indicate a change the opcode in the following byte. For instance
// for branches it indicates a long (16 bit) branch.

enum class Op : uint8_t {
    ILL, Page2, Page3, ABX, ADC, ADD, AND, ANDCC, 
    ASR, BCC, BCS, BEQ, BGE, BGT, BHI, BHS, 
    BIT, BLE, BLO, BLS, BLT, BMI, BNE, BPL, 
    BRA, BRN, BSR, BVC, BVS, CLR, CMP, COM, 
    CWAI, DAA, DEC, EOR, EXG, INC, JMP, JSR, 
    LD, LEA, LSL, LSR, MUL, NEG, NOP, OR, 
    ORCC, PSHS, PSHU, PULS, PULU, ROL, ROR, RTI, 
    RTS, SBC, SEX, ST, SUB, SWI, SWI2, SWI3, 
    SYNC, TFR, TST, FIRQ, IRQ, NMI, RESTART
};

enum class Adr : uint8_t { None, Direct, Inherent, Relative, Immed, Indexed, Extended };

struct Opcode
{
    Op op : 6;
    Adr adr : 3;
    uint8_t cycles : 3;
    uint8_t bytes : 2;
};

static constexpr Opcode opcodeTable[ ] = {
    /*00*/  	{ Op::NEG	  , Adr::Direct	   , 6	    , 2 },
    /*01*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*02*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*03*/  	{ Op::COM	  , Adr::Direct	   , 6	    , 2 },
    /*04*/  	{ Op::LSR	  , Adr::Direct	   , 6	    , 2 },
    /*05*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*06*/  	{ Op::ROR	  , Adr::Direct	   , 6	    , 2 },
    /*07*/  	{ Op::ASR	  , Adr::Direct	   , 6	    , 2 },
    /*08*/  	{ Op::LSL	  , Adr::Direct	   , 6	    , 2 },
    /*09*/  	{ Op::ROL	  , Adr::Direct	   , 6	    , 2 },
    /*0A*/  	{ Op::DEC	  , Adr::Direct	   , 6	    , 2 },
    /*0B*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*0C*/  	{ Op::INC	  , Adr::Direct	   , 6	    , 2 },
    /*0D*/  	{ Op::TST	  , Adr::Direct	   , 6	    , 2 },
    /*0E*/  	{ Op::JMP	  , Adr::Direct	   , 3	    , 2 },
    /*0F*/  	{ Op::CLR	  , Adr::Direct	   , 6	    , 2 },

    /*10*/  	{ Op::Page2	  , Adr::None	   , 0	    , 0 },
    /*11*/  	{ Op::Page3	  , Adr::None	   , 0	    , 0 },
    /*12*/  	{ Op::NOP	  , Adr::Inherent	,2	    , 1 },
    /*13*/  	{ Op::SYNC	  , Adr::Inherent	,4	    , 1 },
    /*14*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*15*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*16*/  	{ Op::LBRA	  , Adr::Relative	,5	    , 3 },
    /*17*/  	{ Op::LBSR	  , Adr::Relative	,9	    , 3 },
    /*18*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*19*/  	{ Op::DAA	  , Adr::Inherent	,2	    , 1 },
    /*1A*/  	{ Op::ORCC	  , Adr::Immed	   , 3	    , 2 },
    /*1B*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*1C*/  	{ Op::ANDCC	  , Adr::Immed	   , 3	    , 2 },
    /*1D*/  	{ Op::SEX	  , Adr::Inherent	,2	    , 1 },
    /*1E*/  	{ Op::EXG	  , Adr::Immed	   , 8	    , 2 },
    /*1F*/  	{ Op::TFR	  , Adr::Immed	   , 6	    , 2 },

    /*20*/  	{ Op::BRA	  , Adr::Relative	,3	    , 2 },
    /*21*/  	{ Op::BRN	  , Adr::Relative	,3	    , 2 },
    /*22*/  	{ Op::BHI	  , Adr::Relative	,3	    , 2 },
    /*23*/  	{ Op::BLS	  , Adr::Relative	,3	    , 2 },
    /*24*/  	{ Op::BHS	  , Adr::Relative	,3	    , 2 },
    /*25*/  	{ Op::BLO	  , Adr::Relative	,3	    , 2 },
    /*26*/  	{ Op::BNE	  , Adr::Relative	,3	    , 2 },
    /*27*/  	{ Op::BEQ	  , Adr::Relative	,3	    , 2 },
    /*28*/  	{ Op::BVC	  , Adr::Relative	,3	    , 2 },
    /*29*/  	{ Op::BVS	  , Adr::Relative	,3	    , 2 },
    /*2A*/  	{ Op::BPL	  , Adr::Relative	,3	    , 2 },
    /*2B*/  	{ Op::BMI	  , Adr::Relative	,3	    , 2 },
    /*2C*/  	{ Op::BGE	  , Adr::Relative	,3	    , 2 },
    /*2D*/  	{ Op::BLT	  , Adr::Relative	,3	    , 2 },
    /*2E*/  	{ Op::BGT	  , Adr::Relative	,3	    , 2 },
    /*2F*/  	{ Op::BLE	  , Adr::Relative	,3	    , 2 },

    /*30*/  	{ Op::LEAX	  , Adr::Indexed	   , 4+	    , 2+ },
    /*31*/  	{ Op::LEAY	  , Adr::Indexed	   , 4+	    , 2+ },
    /*32*/  	{ Op::LEAS	  , Adr::Indexed	   , 4+	    , 2+ },
    /*33*/  	{ Op::LEAU	  , Adr::Indexed	   , 4+	    , 2+ },
    /*34*/  	{ Op::PSHS	  , Adr::Immed	   , 5+	    , 2 },
    /*35*/  	{ Op::PULS	  , Adr::Immed	   , 5+	    , 2 },
    /*36*/  	{ Op::PSHU	  , Adr::Immed	   , 5+	    , 2 },
    /*37*/  	{ Op::PULU	  , Adr::Immed	   , 5+	    , 2 },
    /*38*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*39*/  	{ Op::RTS	  , Adr::Inherent	,5	    , 1 },
    /*3A*/  	{ Op::ABX	  , Adr::Inherent	,3	    , 1 },
    /*3B*/  	{ Op::RTI	  , Adr::Inherent	,6/15	, 1 },
    /*3C*/  	{ Op::CWAI	  , Adr::Inherent	,20	    , 2 },
    /*3D*/  	{ Op::MUL	  , Adr::Inherent	,11	    , 1 },
    /*3E*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*3F*/  	{ Op::SWI	  , Adr::Inherent	,19	    , 1 },

    /*40*/  	{ Op::NEGA	  , Adr::Inherent	,2	    , 1 },
    /*41*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*42*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*43*/  	{ Op::COMA	  , Adr::Inherent	,2	    , 1 },
    /*44*/  	{ Op::LSRA	  , Adr::Inherent	,2	    , 1 },
    /*45*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*46*/  	{ Op::RORA	  , Adr::Inherent	,2	    , 1 },
    /*47*/  	{ Op::ASRA	  , Adr::Inherent	,2	    , 1 },
    /*48*/  	{ Op::LSLA	  , Adr::Inherent	,2	    , 1 },
    /*49*/  	{ Op::ROLA	  , Adr::Inherent	,2	    , 1 },
    /*4A*/  	{ Op::DECA	  , Adr::Inherent	,2	    , 1 },
    /*4B*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*4C*/  	{ Op::INCA	  , Adr::Inherent	,2	    , 1 },
    /*4D*/  	{ Op::TSTA	  , Adr::Inherent	,2	    , 1 },
    /*4E*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*4F*/  	{ Op::CLRA	  , Adr::Inherent	,2	    , 1 },

    /*50*/  	{ Op::NEGB	  , Adr::Inherent	,2	    , 1 },
    /*51*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*52*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*53*/  	{ Op::COMB	  , Adr::Inherent	,2	    , 1 },
    /*54*/  	{ Op::LSRB	  , Adr::Inherent	,2	    , 1 },
    /*55*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*56*/  	{ Op::RORB	  , Adr::Inherent	,2	    , 1 },
    /*57*/  	{ Op::ASRB	  , Adr::Inherent	,2	    , 1 },
    /*58*/  	{ Op::LSLB	  , Adr::Inherent	,2	    , 1 },
    /*59*/  	{ Op::ROLB	  , Adr::Inherent	,2	    , 1 },
    /*5A*/  	{ Op::DECB	  , Adr::Inherent	,2	    , 1 },
    /*5B*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*5C*/  	{ Op::INCB	  , Adr::Inherent	,2	    , 1 },
    /*5D*/  	{ Op::TSTB	  , Adr::Inherent	,2	    , 1 },
    /*5E*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*5F*/  	{ Op::CLRB	  , Adr::Inherent	,2	    , 1 },

    /*60*/  	{ Op::NEG	  , Adr::Indexed	   , 6+	    , 2+ },
    /*61*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*62*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*63*/  	{ Op::COM	  , Adr::Indexed	   , 6+	    , 2+ },
    /*64*/  	{ Op::LSR	  , Adr::Indexed	   , 6+	    , 2+ },
    /*65*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*66*/  	{ Op::ROR	  , Adr::Indexed	   , 6+	    , 2+ },
    /*67*/  	{ Op::ASR	  , Adr::Indexed	   , 6+	    , 2+ },
    /*68*/  	{ Op::LSL	  , Adr::Indexed	   , 6+	    , 2+ },
    /*69*/  	{ Op::ROL	  , Adr::Indexed	   , 6+	    , 2+ },
    /*6A*/  	{ Op::DEC	  , Adr::Indexed	   , 6+	    , 2+ },
    /*6B*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*6C*/  	{ Op::INC	  , Adr::Indexed	   , 6+	    , 2+ },
    /*6D*/  	{ Op::TST	  , Adr::Indexed	   , 6+	    , 2+ },
    /*6E*/  	{ Op::JMP	  , Adr::Indexed	   , 3+	    , 2+ },
    /*6F*/  	{ Op::CLR	  , Adr::Indexed	   , 6+	    , 2+ },

    /*70*/  	{ Op::NEG	  , Adr::Extended	,7	    , 3 },
    /*71*/  	{ Op::ILL	  , Adr::None	   , 0	    , 0 },
    /*72*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*73*/  	{ Op::COM	  , Adr::Extended	,7	    , 3 },
    /*74*/  	{ Op::LSR	  , Adr::Extended	,7	    , 3 },
    /*75*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*76*/  	{ Op::ROR	  , Adr::Extended	,7	    , 3 },
    /*77*/  	{ Op::ASR	  , Adr::Extended	,7	    , 3 },
    /*78*/  	{ Op::LSL	  , Adr::Extended	,7	    , 3 },
    /*79*/  	{ Op::ROL	  , Adr::Extended	,7	    , 3 },
    /*7A*/  	{ Op::DEC	  , Adr::Extended	,7	    , 3 },
    /*7B*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*7C*/  	{ Op::INC	  , Adr::Extended	,7	    , 3 },
    /*7D*/  	{ Op::TST	  , Adr::Extended	,7	    , 3 },
    /*7E*/  	{ Op::JMP	  , Adr::Extended	,4	    , 3 },
    /*7F*/  	{ Op::CLR	  , Adr::Extended	,7	    , 3 },

    /*80*/  	{ Op::SUBA	  , Adr::Immed	   , 2	    , 2 },
    /*81*/  	{ Op::CMPA	  , Adr::Immed	   , 2	    , 2 },
    /*82*/  	{ Op::SBCA	  , Adr::Immed	   , 2	    , 2 },
    /*83*/  	{ Op::SUBD	  , Adr::Immed	   , 4	    , 3 },
    /*84*/  	{ Op::ANDA	  , Adr::Immed	   , 2	    , 2 },
    /*85*/  	{ Op::BITA	  , Adr::Immed	   , 2	    , 2 },
    /*86*/  	{ Op::LDA	  , Adr::Immed	   , 2	    , 2 },
    /*87*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*88*/  	{ Op::EORA	  , Adr::Immed	   , 2	    , 2 },
    /*89*/  	{ Op::ADCA	  , Adr::Immed	   , 2	    , 2 },
    /*8A*/  	{ Op::ORA	  , Adr::Immed	   , 2	    , 2 },
    /*8B*/  	{ Op::ADDA	  , Adr::Immed	   , 2	    , 2 },
    /*8C*/  	{ Op::CMPX	  , Adr::Immed	   , 4	    , 3 },
    /*8D*/  	{ Op::BSR	  , Adr::Relative   , 7	    , 2 },
    /*8E*/  	{ Op::LDX	  , Adr::Immed	   , 3	    , 3 },
    /*8F*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },

    /*90*/  	{ Op::SUBA	  , Adr::Direct	   , 4	    , 2 },
    /*91*/  	{ Op::CMPA	  , Adr::Direct	   , 4	    , 2 },
    /*92*/  	{ Op::SBCA	  , Adr::Direct	   , 4	    , 2 },
    /*93*/  	{ Op::SUBD	  , Adr::Direct	   , 6	    , 2 },
    /*94*/  	{ Op::ANDA	  , Adr::Direct	   , 4	    , 2 },
    /*95*/  	{ Op::BITA	  , Adr::Direct	   , 4	    , 2 },
    /*96*/  	{ Op::LDA	  , Adr::Direct	   , 4	    , 2 },
    /*97*/  	{ Op::STA	  , Adr::Direct	   , 4	    , 2 },
    /*98*/  	{ Op::EORA	  , Adr::Direct	   , 4	    , 2 },
    /*99*/  	{ Op::ADCA	  , Adr::Direct	   , 4	    , 2 },
    /*9A*/  	{ Op::ORA	  , Adr::Direct	   , 4	    , 2 },
    /*9B*/  	{ Op::ADDA	  , Adr::Direct	   , 4	    , 2 },
    /*9C*/  	{ Op::CMPX	  , Adr::Direct	   , 6	    , 2 },
    /*9D*/  	{ Op::JSR	  , Adr::Direct	   , 7	    , 2 },
    /*9E*/  	{ Op::LDX	  , Adr::Direct	   , 5	    , 2 },
    /*9F*/  	{ Op::STX	  , Adr::Direct	   , 5	    , 2 },

    /*A0*/  	{ Op::SUBA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A1*/  	{ Op::CMPA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A2*/  	{ Op::SBCA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A3*/  	{ Op::SUBD	  , Adr::Indexed	   , 6+	    , 2+ },
    /*A4*/  	{ Op::ANDA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A5*/  	{ Op::BITA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A6*/  	{ Op::LDA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A7*/  	{ Op::STA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A8*/  	{ Op::EORA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*A9*/  	{ Op::ADCA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*AA*/  	{ Op::ORA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*AB*/  	{ Op::ADDA	  , Adr::Indexed	   , 4+	    , 2+ },
    /*AC*/  	{ Op::CMPX	  , Adr::Indexed	   , 6+	    , 2+ },
    /*AD*/  	{ Op::JSR	  , Adr::Indexed	   , 7+	    , 2+ },
    /*AE*/  	{ Op::LDX	  , Adr::Indexed	   , 5+	    , 2+ },
    /*AF*/  	{ Op::STX	  , Adr::Indexed	   , 5+	    , 2+ },

    /*B0*/  	{ Op::SUBA	  , Adr::Extended	,5	    , 3 },
    /*B1*/  	{ Op::CMPA	  , Adr::Extended	,5	    , 3 },
    /*B2*/  	{ Op::SBCA	  , Adr::Extended	,5	    , 3 },
    /*B3*/  	{ Op::SUBD	  , Adr::Extended	,7	    , 3 },
    /*B4*/  	{ Op::ANDA	  , Adr::Extended	,5	    , 3 },
    /*B5*/  	{ Op::BITA	  , Adr::Extended	,5	    , 3 },
    /*B6*/  	{ Op::LDA	  , Adr::Extended	,5	    , 3 },
    /*B7*/  	{ Op::STA	  , Adr::Extended	,5	    , 3 },
    /*B8*/  	{ Op::EORA	  , Adr::Extended	,5	    , 3 },
    /*B9*/  	{ Op::ADCA	  , Adr::Extended	,5	    , 3 },
    /*BA*/  	{ Op::ORA	  , Adr::Extended	,5	    , 3 },
    /*BB*/  	{ Op::ADDA	  , Adr::Extended	,5	    , 3 },
    /*BC*/  	{ Op::CMPX	  , Adr::Extended	,7	    , 3 },
    /*BD*/  	{ Op::JSR	  , Adr::Extended	,8	    , 3 },
    /*BE*/  	{ Op::LDX	  , Adr::Extended	,6	    , 3 },
    /*BF*/  	{ Op::STX	  , Adr::Extended	,6	    , 3 },

    /*C0*/  	{ Op::SUBB	  , Adr::Immed	   , 2	    , 2 },
    /*C1*/  	{ Op::CMPB	  , Adr::Immed	   , 2	    , 2 },
    /*C2*/  	{ Op::SBCB	  , Adr::Immed	   , 2	    , 2 },
    /*C3*/  	{ Op::ADDD	  , Adr::Immed	   , 4	    , 3 },
    /*C4*/  	{ Op::ANDB	  , Adr::Immed	   , 2	    , 2 },
    /*C5*/  	{ Op::BITB	  , Adr::Immed	   , 2	    , 2 },
    /*C6*/  	{ Op::LDB	  , Adr::Immed	   , 2	    , 2 },
    /*C7*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*C8*/  	{ Op::EORB	  , Adr::Immed	   , 2	    , 2 },
    /*C9*/  	{ Op::ADCB	  , Adr::Immed	   , 2	    , 2 },
    /*CA*/  	{ Op::ORB	  , Adr::Immed	   , 2	    , 2 },
    /*CB*/  	{ Op::ADDB	  , Adr::Immed	   , 2	    , 2 },
    /*CC*/  	{ Op::LDD	  , Adr::Immed	   , 3	    , 3 },
    /*CD*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },
    /*CE*/  	{ Op::LDU	  , Adr::Immed	   , 3	    , 3 },
    /*CF*/  	{ Op::ILL	  , Adr::None       , 0      , 0 },

    /*D0*/  	{ Op::SUBB	  , Adr::Direct	   , 4	    , 2 },
    /*D1*/  	{ Op::CMPB	  , Adr::Direct	   , 4	    , 2 },
    /*D2*/  	{ Op::SBCB	  , Adr::Direct	   , 4	    , 2 },
    /*D3*/  	{ Op::ADDD	  , Adr::Direct	   , 6	    , 2 },
    /*D4*/  	{ Op::ANDB	  , Adr::Direct	   , 4	    , 2 },
    /*D5*/  	{ Op::BITB	  , Adr::Direct	   , 4	    , 2 },
    /*D6*/  	{ Op::LDB	  , Adr::Direct	   , 4	    , 2 },
    /*D7*/  	{ Op::STB	  , Adr::Direct	   , 4	    , 2 },
    /*D8*/  	{ Op::EORB	  , Adr::Direct	   , 4	    , 2 },
    /*D9*/  	{ Op::ADCB	  , Adr::Direct	   , 4	    , 2 },
    /*DA*/  	{ Op::ORB	  , Adr::Direct	   , 4	    , 2 },
    /*DB*/  	{ Op::ADDB	  , Adr::Direct	   , 4	    , 2 },
    /*DC*/  	{ Op::LDD	  , Adr::Direct	   , 5	    , 2 },
    /*DD*/  	{ Op::STD	  , Adr::Direct	   , 5	    , 2 },
    /*DE*/  	{ Op::LDU	  , Adr::Direct	   , 5	    , 2 },
    /*DF*/  	{ Op::STU	  , Adr::Direct	   , 5	    , 2 },

    /*E0*/  	{ Op::SUBB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E1*/  	{ Op::CMPB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E2*/  	{ Op::SBCB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E3*/  	{ Op::ADDD	  , Adr::Indexed	   , 6+	    , 2+ },
    /*E4*/  	{ Op::ANDB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E5*/  	{ Op::BITB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E6*/  	{ Op::LDB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E7*/  	{ Op::STB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E8*/  	{ Op::EORB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*E9*/  	{ Op::ADCB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*EA*/  	{ Op::ORB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*EB*/  	{ Op::ADDB	  , Adr::Indexed	   , 4+	    , 2+ },
    /*EC*/  	{ Op::LDD	  , Adr::Indexed	   , 5+	    , 2+ },
    /*ED*/  	{ Op::STD	  , Adr::Indexed	   , 5+	    , 2+ },
    /*EE*/  	{ Op::LDU	  , Adr::Indexed	   , 5+	    , 2+ },
    /*EF*/  	{ Op::STU	  , Adr::Indexed	   , 5+	    , 2+ },

    /*F0*/  	{ Op::SUBB	  , Adr::Extended	,5	    , 3 },
    /*F1*/  	{ Op::CMPB	  , Adr::Extended	,5	    , 3 },
    /*F2*/  	{ Op::SBCB	  , Adr::Extended	,5	    , 3 },
    /*F3*/  	{ Op::ADDD	  , Adr::Extended	,7	    , 3 },
    /*F4*/  	{ Op::ANDB	  , Adr::Extended	,5	    , 3 },
    /*F5*/  	{ Op::BITB	  , Adr::Extended	,5	    , 3 },
    /*F6*/  	{ Op::LDB	  , Adr::Extended	,5	    , 3 },
    /*F7*/  	{ Op::STB	  , Adr::Extended	,5	    , 3 },
    /*F8*/  	{ Op::EORB	  , Adr::Extended	,5	    , 3 },
    /*F9*/  	{ Op::ADCB	  , Adr::Extended	,5	    , 3 },
    /*FA*/  	{ Op::ORB	  , Adr::Extended	,5	    , 3 },
    /*FB*/  	{ Op::ADDB	  , Adr::Extended	,5	    , 3 },
    /*FC*/  	{ Op::LDD	  , Adr::Extended	,6	    , 3 },
    /*FD*/  	{ Op::STD	  , Adr::Extended	,6	    , 3 },
    /*FE*/  	{ Op::LDU	  , Adr::Extended	,6	    , 3 },
    /*FF*/  	{ Op::STU	  , Adr::Extended	,6	    , 3 },
};
